/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CaptchaButton: typeof import('./components/CaptchaButton.vue')['default']
    CheckinTimeline: typeof import('./components/CheckinTimeline.vue')['default']
    CrowdFlow: typeof import('./components/CrowdFlow.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LevelProgress: typeof import('./components/LevelProgress.vue')['default']
    MedalWall: typeof import('./components/MedalWall.vue')['default']
    NavigationCard: typeof import('./components/NavigationCard.vue')['default']
    OpeningHoursReminder: typeof import('./components/OpeningHoursReminder.vue')['default']
    OpeningStatus: typeof import('./components/OpeningStatus.vue')['default']
    OpenStatus: typeof import('./components/OpenStatus.vue')['default']
    OpenTimeStatus: typeof import('./components/OpenTimeStatus.vue')['default']
    PosterGenerator: typeof import('./components/PosterGenerator.vue')['default']
    RatingStars: typeof import('./components/RatingStars.vue')['default']
    ReviewForm: typeof import('./components/ReviewForm.vue')['default']
    ReviewItem: typeof import('./components/ReviewItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInCalendar: typeof import('./components/SignInCalendar.vue')['default']
    SignInReward: typeof import('./components/SignInReward.vue')['default']
    TabBar: typeof import('./components/TabBar.vue')['default']
    TodayRecommend: typeof import('./components/TodayRecommend.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanProgress: typeof import('vant/es')['Progress']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VisitRoute: typeof import('./components/VisitRoute.vue')['default']
  }
}
